# Site settings
title: Becoming a Developer
header-img: img/home-bg.png
email: dcunn6@gmail.com
copyright_name: 100katl
description: > # this means to ignore newlines until "baseurl:"
  My Journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  100katl
learn_profile: 100katl
email_username: dcunn6@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
